footer:
  framework: 框架
  theme: 主題

copy:
  success: 複製成功
  error: 複製錯誤
  noSupport: 瀏覽器不支持

page:
  articles: 文章總覽
  tag: 標籤
  category: 分類
  archives: 歸檔

card_post_count: 條評論

sticky: 置頂
no_title: 無題

post:
  created: 發表於
  updated: 更新於
  wordcount: 字數統計
  min2read: 閱讀時間
  min2read_unit: 分鐘
  page_pv: 點閱量
  comments: 評論數
  copyright:
    author: 文章作者
    link: 文章網址
    copyright_notice: 版權聲明
    copyright_content: '本博客所有文章除特別聲明外，均采用
      <a href="%s" target="_blank">%s</a> 許可協議。轉載請註明來自 <a href="%s" target="_blank">%s</a>！'
  recommend: 喜歡這篇文章的人也看了
  edit: 編輯

search:
  title: "搜索"
  load_data: 資料庫載入中
  algolia_search:
    input_placeholder: 輸入關鍵字後按下 ENTER 查找
    hits_empty: "找不到您查詢的內容：${query}"
    hits_stats: "找到 ${hits} 條結果，用時 ${time} 毫秒"

  local_search:
    input_placeholder: 搜索文章
    hits_empty: "找不到您查詢的內容：${query}"

pagination:
  prev: 上一篇
  next: 下一篇

comment: 評論

aside:
  articles: 文章
  tags: 標籤
  categories: 分類
  card_announcement: 公告
  card_categories: 分類
  card_tags: 標籤
  card_archives: 歸檔
  card_recent_post: 最近發布
  card_webinfo:
    headline: 網站資訊
    article_name: 文章總數
    runtime:
      name: 建站天數
      unit: 天
    last_push_date:
      name: 最后更新時間
    site_wordcount: 全站字數
    site_uv_name: 全站訪客數
    site_pv_name: 全站總訪問量
  more_button: 查看更多
  card_newest_comments:
    headline: 最新評論
    loading_text: 正在加載中...
    error: 無法取得評論，請確認相關配置是否正確
    zero: 沒有評論
    image: 圖片
    link: 網址
    code: 程式碼
  card_toc: 文章目錄
  display_mode: 顯示模式
  function: 功能

date_suffix:
  just: 剛剛
  min: 分鐘前
  hour: 小時前
  day: 天前
  month: 個月前

donate: 不給糖果就搗蛋
share: 分享

rightside:
  readmode_title: 閱讀模式
  translate_title: 簡繁轉換
  night_mode_title: 淺色和深色模式轉換
  back_to_top: 回到頂部
  toc: 目錄
  scroll_to_comment: 直達評論
  setting: 設定
  aside: 單欄和雙欄切換
  chat: 聊天

copy_copyright:
  author: 作者
  link: 網址
  source: 來源
  info: 著作權歸作者所有。商業轉載請聯絡作者授權，非商業轉載請註明出處。
  copySuccess: 複製成功，複製轉載請標註本文網址

Snackbar:
  chs_to_cht: 你已切換為繁體
  cht_to_chs: 你已切换为简体
  day_to_night: 你已切換為深色模式
  night_to_day: 你已切換為淺色模式
  copy_equipment_name: 已複製裝備名稱

loading: 加載中...

load_more: 加載更多

error404: 頁面沒有找到
